sudo: false

language: node_js
before_install: 
 - bundler install --path vendor/bundle
install:
 - npm install
 - node_modules/.bin/bower install
script: node_modules/.bin/grunt build

addons:
  ssh_known_hosts: premium.raumzeitlabor.de
after_success:
  - ./deploy.sh

cache:
  bundler: true
  directories:
    - node_modules
    - vendor/bundle
    - app/bower_components

env:
  global:
    - ENCRYPTION_LABEL="906c0d008fb2"
    - DEPLOY_BRANCH="master"
