language: node_js
before_install: 
 - gem install jekyll
 - npm install -g grunt-cli bower
install: npm install
script: grunt build

addons:
  ssh_known_hosts: premium.raumzeitlabor.de
after_success:
  - ./deploy.sh

env:
  global:
    - ENCRYPTION_LABEL="906c0d008fb2"
    - DEPLOY_BRANCH="master"
